name       : perl-data-uuid
version    : '1.221'
release    : 5
source     :
    - https://github.com/rjbs/Data-UUID/archive/1.221.tar.gz : e90415b840a51437c3bfcfd6a0cff4d072898b397d42fc225d9b93f219524a5d
license    : BSD-4-Clause
component  : programming.perl
homepage   : https://github.com/rjbs/Data-UUID
summary    : Perl extension for generating Globally/Universally Unique Identifiers
description: |
    This module provides a framework for generating UUIDs (Universally Unique Identifiers, also known as GUIDs (Globally Unique Identifiers).
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
